### ISSUE TITLE
AfterLevelMenu

### ISSUE THREAD

**Issue by fuchss-dominik** [fuchss-dominik/rekit-game#25] opened 2016-07-24 17:45 UTC
Originally reported by: **Angelo Aracri (Bitbucket: [AnJ95](https://bitbucket.org/AnJ95), GitHub: [AnJ95](https://github.com/AnJ95))**

----------------------------------------

Create menu that appears after
```
#!java
LevelScene.end(boolean won)
```
depending on if Level is *infinite* or *arcade* and if *won* or *!won*, there are different buttons

* Infinite+Lost: "Try again" & "Back"
* Infinite+Won: ... Does not exist
* Arcade+Lost: "Try again" & "Back"
* Arcade+Won: "Next" & "Back"

----------------------------------------
- Bitbucket: https://bitbucket.org/AnJ95/projectragnarok/issue/25

**Comment by matzebond** [comment] 2017-03-24 14:44
Closed because of  	c87f2c6 and this is sort of a duplicate of #2

**Closed by matzebond** 2017-03-24 14:44 UTC
Labels: enhancement, major
